#!/bin/sh

post_install() {
    # remove hwclock service
    /usr/lib/rc/sv.d/hwclock stop

    # assign swclock-offset services
    /usr/lib/rc/sv.d/swclock-offset-boot start
    /usr/lib/rc/sv.d/swclock-offset-shutdown start
}

pre_remove() {
    # Restore the original state

    # remove swclock-offset services
    /usr/lib/rc/sv.d/swclock-offset-boot stop
    /usr/lib/rc/sv.d/swclock-offset-shutdown stop

    # assign hwclock service
    /usr/lib/rc/sv.d/hwclock start
}
