#!/bin/sh

post_install() {
    # remove hwclock service
    s6-service del misc hwclock

    # assign swclock-offset services
    s6-service add misc swclock-offset-boot
	s6-service add misc swclock-offset-shutdown

    # reload database
    s6-db-reload
}

pre_remove() {
    # Restore the original state

    # remove swclock-offset services
    s6-service del misc swclock-offset-boot 
	s6-service del misc swclock-offset-shutdown

    # assign hwclock service
    s6-service add misc hwclock

    # reload database
    s6-db-reload
}