# Xiaomi Pad 6 specific hexagonrpcd firmware directory
hexagonrpcd_fw_dir="/usr/share/qcom/sm8250/Xiaomi/pipa/"

# Arguments for hexagonrpcd
adsp_rootpd_args="-f /dev/fastrpc-adsp -d adsp"
adsp_sensorspd_args="-f /dev/fastrpc-adsp -d adsp -s"
sdsp_args="-f /dev/fastrpc-sdsp -d sdsp -s"
